# spring:
#   application:
#     name: eureka-server
# 
# server:
#   port: 8761
#   ssl:
#     enabled: true
#     client-auth: need
#     key-store: classpath:eureka.jks
#     key-store-password: bsep123
#     key-alias: eureka
#     trust-store: classpath:eureka.jks
#     trust-store-password: bsep123
#     
# eureka:
#   instance:
#     securePort: ${server.port}
#     securePortEnabled: true
#     prefer-ip-address: true
#     nonSecurePortEnabled: false 
#   client:
#     registerWithEureka: false