# server:  
#   port: ${PORT:8900}
#   ssl:
#     enabled: true
#     key-store: classpath:mess.jks
#     key-store-password: password
#     key-alias: mess
#     
# security:
#   require-ssl: true
# eureka:
#   instance:
#     hostname: localhost
#     prefer-ip-address: false
#     nonSecurePortEnabled: false
#     securePortEnabled: true
#     securePort: ${server.port}
#   client:
#     securePortEnabled: true
#     serviceUrl:
#       defaultZone: https://localhost:8761/eureka/ 