# spring:
#   application:
#     name: zuul-server
# server:  
#   port: ${PORT:8672}
#   ssl:
#     enabled: true
#     key-store: classpath:zuul.jks
#     key-store-password: bsep123
#     key-alias: zuul
#     
# security:
#   require-ssl: false
# eureka:
#   instance:
#     hostname: localhost
#     prefer-ip-address: false
#     nonSecurePortEnabled: false
#     securePortEnabled: true
#     securePort: ${server.port}
#   client:
#     securePortEnabled: true
#     serviceUrl:
#       defaultZone: https://localhost:8761/eureka/ 
# 
# ribbon:
#   IsSecured: true
#   ConnectTimeout:  10000
#   ReadTimeout:  10000
#   eureka:
#     enabled: true
#   TrustStore: classpath:zuul.jks
#   TrustStorePassword : bsep123
#   IsHostnameValidationRequired: false