//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 02:14:23 PM CEST 
//


package xml_bsep.rating_system.model;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.validation.annotation.Validated;


@Validated
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recension", propOrder = {
    "comment",
    "rating",
    "id",
    "status",
    "user",
    "accomodationUnit"
})
public class Recension {

	@NotBlank
    @XmlElement(required = true)
    protected String comment;

	@Min(1)
	@Max(5)
    protected int rating;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement(required = true)
    protected long id;
    
    @XmlElement(defaultValue = "false")
    protected RecensionStatus status;
    
    @ManyToOne(cascade = CascadeType.REFRESH)
    @JoinColumn(name = "user_id", foreignKey = @ForeignKey(name = "RECENSION_USER_ID_FK"))
    @XmlElement(required = true)
    protected User user;
    
    @ManyToOne(cascade = CascadeType.REFRESH)
    @JoinColumn(name = "accomodation_unit_id", foreignKey = @ForeignKey(name = "RECENSION_ACC_UNIT_ID_FK"))
    @XmlElement(name = "accomodation_unit", required = true)
    protected AccomodationUnit accomodationUnit;

    public Recension() {
    	
    }
    
    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public int getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(int value) {
        this.rating = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the accomodationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationUnit }
     *     
     */
    public AccomodationUnit getAccomodationUnit() {
        return accomodationUnit;
    }

    /**
     * Sets the value of the accomodationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationUnit }
     *     
     */
    public void setAccomodationUnit(AccomodationUnit value) {
        this.accomodationUnit = value;
    }

	public RecensionStatus getStatus() {
		return status;
	}

	public void setStatus(RecensionStatus status) {
		this.status = status;
	}

    
    
}
