FROM openjdk:8
MAINTAINER Miljan Cabrilo <miljancabrilo@yahoo.com>
ADD target/spring-eureka-auth-0.0.1-SNAPSHOT.jar spring-eureka-auth.jar
ENTRYPOINT ["java", "-jar", "./spring-eureka-auth.jar"]
EXPOSE 9100