FROM anapsix/alpine-java
MAINTAINER Miljan Cabrilo <miljancabrilo@yahoo.com>
ADD target/spring-eureka-zuul-0.0.1-SNAPSHOT.jar spring-eureka-zuul.jar
ENTRYPOINT ["java", "-jar", "./spring-eureka-zuul.jar"]
EXPOSE 8762